"use client";

import {
  Activity,
  AlertTriangle,
  Anchor,
  Antenna,
  Archive,
  ArrowLeftRight,
  Atom,
  BadgeAlert,
  BadgeCheck,
  Ban,
  Bell,
  Binary,
  Blocks,
  Bluetooth,
  Bolt,
  BookOpen,
  Bot,
  BotMessageSquare,
  Box,
  Brain,
  BrainCircuit,
  BrainCog,
  Bug,
  Building2,
  Cable,
  Camera,
  Cctv,
  ChartBar,
  CircuitBoard,
  Clock,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Code,
  Cog,
  Compass,
  Container,
  Cpu,
  Crosshair,
  Database,
  DatabaseBackup,
  DatabaseZap,
  Download,
  Eye,
  File,
  FileCode,
  Filter,
  Fingerprint,
  Flame,
  Folder,
  Funnel,
  Gauge,
  GitBranch,
  GitMerge,
  Globe,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  Hash,
  Headphones,
  Heart,
  Image,
  Infinity,
  Key,
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link,
  Locate,
  Lock,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  Merge,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Network,
  Orbit,
  Package,
  Palette,
  Phone,
  Plug,
  Podcast,
  Power,
  Printer,
  QrCode,
  Radar,
  Radio,
  RadioTower,
  RefreshCw,
  Repeat,
  Rocket,
  Router,
  Rss,
  Satellite,
  SatelliteDish,
  ScanEye,
  ScanFace,
  ScanLine,
  Scale,
  Search,
  Send,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldHalf,
  ShieldMinus,
  ShieldPlus,
  Shuffle,
  Signal,
  Siren,
  Smartphone,
  Sparkles,
  Speaker,
  Split,
  Star,
  Swords,
  Tablet,
  Target,
  Terminal,
  Thermometer,
  Timer,
  Tv,
  Ungroup,
  Unlock,
  Upload,
  Usb,
  User,
  Users,
  Video,
  Wallet,
  WandSparkles,
  Waypoints,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  anchor: Anchor,
  antenna: Antenna,
  archive: Archive,
  "arrow-left-right": ArrowLeftRight,
  atom: Atom,
  "badge-alert": BadgeAlert,
  "badge-check": BadgeCheck,
  ban: Ban,
  bell: Bell,
  binary: Binary,
  blocks: Blocks,
  bluetooth: Bluetooth,
  bolt: Bolt,
  "book-open": BookOpen,
  bot: Bot,
  "bot-message": BotMessageSquare,
  box: Box,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  "brain-cog": BrainCog,
  bug: Bug,
  building: Building2,
  cable: Cable,
  camera: Camera,
  cctv: Cctv,
  "chart-bar": ChartBar,
  "circuit-board": CircuitBoard,
  clock: Clock,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  "cloud-download": CloudDownload,
  "cloud-off": CloudOff,
  "cloud-upload": CloudUpload,
  code: Code,
  cog: Cog,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  crosshair: Crosshair,
  database: Database,
  "database-backup": DatabaseBackup,
  "database-zap": DatabaseZap,
  download: Download,
  eye: Eye,
  file: File,
  "file-code": FileCode,
  filter: Filter,
  fingerprint: Fingerprint,
  flame: Flame,
  folder: Folder,
  funnel: Funnel,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  globe: Globe,
  "hard-drive": HardDrive,
  "hard-drive-download": HardDriveDownload,
  "hard-drive-upload": HardDriveUpload,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  image: Image,
  infinity: Infinity,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  "layout-grid": LayoutGrid,
  lightbulb: Lightbulb,
  link: Link,
  locate: Locate,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  merge: Merge,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  network: Network,
  orbit: Orbit,
  package: Package,
  palette: Palette,
  phone: Phone,
  plug: Plug,
  podcast: Podcast,
  power: Power,
  printer: Printer,
  "qr-code": QrCode,
  radar: Radar,
  radio: Radio,
  "radio-tower": RadioTower,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  router: Router,
  rss: Rss,
  satellite: Satellite,
  "satellite-dish": SatelliteDish,
  "scan-eye": ScanEye,
  "scan-face": ScanFace,
  "scan-line": ScanLine,
  scale: Scale,
  search: Search,
  send: Send,
  server: Server,
  "server-cog": ServerCog,
  "server-crash": ServerCrash,
  "server-off": ServerOff,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-ban": ShieldBan,
  "shield-check": ShieldCheck,
  "shield-half": ShieldHalf,
  "shield-minus": ShieldMinus,
  "shield-plus": ShieldPlus,
  shuffle: Shuffle,
  signal: Signal,
  siren: Siren,
  smartphone: Smartphone,
  sparkles: Sparkles,
  speaker: Speaker,
  split: Split,
  star: Star,
  swords: Swords,
  tablet: Tablet,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  timer: Timer,
  tv: Tv,
  ungroup: Ungroup,
  unlock: Unlock,
  upload: Upload,
  usb: Usb,
  user: User,
  users: Users,
  video: Video,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  waypoints: Waypoints,
  webhook: Webhook,
  wifi: Wifi,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export const iconNames = Object.keys(iconMap);
