"use client";

import {
  Activity,
  Anchor,
  Archive,
  Atom,
  Bell,
  Binary,
  Blocks,
  Bluetooth,
  Bolt,
  BookOpen,
  Bot,
  BotMessageSquare,
  Box,
  Brain,
  BrainCircuit,
  BrainCog,
  Bug,
  Building2,
  Cable,
  Camera,
  ChartBar,
  CircuitBoard,
  Clock,
  Cloud,
  CloudCog,
  Code,
  Cog,
  Container,
  Cpu,
  Database,
  Eye,
  File,
  FileCode,
  Fingerprint,
  Flame,
  Folder,
  Globe,
  HardDrive,
  Headphones,
  Heart,
  Image,
  Infinity,
  Key,
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link,
  Lock,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Network,
  Orbit,
  Package,
  Palette,
  Phone,
  Plug,
  Podcast,
  Power,
  Printer,
  QrCode,
  Radio,
  RefreshCw,
  Rocket,
  Router,
  Rss,
  ScanEye,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Signal,
  Smartphone,
  Sparkles,
  Speaker,
  Star,
  Tablet,
  Terminal,
  Thermometer,
  Timer,
  Tv,
  Upload,
  Usb,
  User,
  Users,
  Video,
  Wallet,
  WandSparkles,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  archive: Archive,
  atom: Atom,
  bell: Bell,
  binary: Binary,
  blocks: Blocks,
  bluetooth: Bluetooth,
  bolt: Bolt,
  "book-open": BookOpen,
  bot: Bot,
  "bot-message": BotMessageSquare,
  box: Box,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  "brain-cog": BrainCog,
  bug: Bug,
  building: Building2,
  cable: Cable,
  camera: Camera,
  "chart-bar": ChartBar,
  "circuit-board": CircuitBoard,
  clock: Clock,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  code: Code,
  cog: Cog,
  container: Container,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  file: File,
  "file-code": FileCode,
  fingerprint: Fingerprint,
  flame: Flame,
  folder: Folder,
  globe: Globe,
  "hard-drive": HardDrive,
  headphones: Headphones,
  heart: Heart,
  image: Image,
  infinity: Infinity,
  key: Key,
  laptop: Laptop,
  layers: Layers,
  "layout-grid": LayoutGrid,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  mail: Mail,
  map: Map,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  network: Network,
  orbit: Orbit,
  package: Package,
  palette: Palette,
  phone: Phone,
  plug: Plug,
  podcast: Podcast,
  power: Power,
  printer: Printer,
  "qr-code": QrCode,
  radio: Radio,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  router: Router,
  rss: Rss,
  "scan-eye": ScanEye,
  scale: Scale,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  signal: Signal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  speaker: Speaker,
  star: Star,
  tablet: Tablet,
  terminal: Terminal,
  thermometer: Thermometer,
  timer: Timer,
  tv: Tv,
  upload: Upload,
  usb: Usb,
  user: User,
  users: Users,
  video: Video,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  webhook: Webhook,
  wifi: Wifi,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export const iconNames = Object.keys(iconMap);
